/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metromendeleyloutphiruizzaheraldeen;

import javax.swing.JOptionPane;

/**
 *
 * @author ayahzaheraldeen
 */
public class AddDirectAbstract extends javax.swing.JFrame {

    private App app;

    /**
     * Creates new form AddDirectAbstract
     */
    public AddDirectAbstract(App app) {
        initComponents();
        this.app = app;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private boolean validateFields() {
        if (TitleFetched.getText().isEmpty() ||
                jTextArea1.getText().isEmpty() ||
                AuthorsFetched.getText().isEmpty() ||
                KeywordsFetched.getText().isEmpty()) {
            return false;
        }

        return true;
    }

    private boolean getFormattedInformation() {
        String title = TitleFetched.getText().trim();
        String authors = AuthorsFetched.getText().trim();
        String text = jTextArea1.getText().trim();
        String keywords = KeywordsFetched.getText().trim();

        String[] authorsArray = authors.split("[,\n]");
        StringBuilder formattedInfo = new StringBuilder();

        formattedInfo.append(title).append("\n\n");

        formattedInfo.append("Autores").append("\n");
        for (String author : authorsArray) {
            formattedInfo.append(author.trim()).append("\n");
        }

        formattedInfo.append("Resumen ").append("\n").append(text).append("\n\n");

        formattedInfo.append("Palabras Claves: ").append(keywords.replace(",", ", ")).append("\n");
        return app.addStringtoHashTables(formattedInfo.toString());
    }

    private void clearFields() {
        TitleFetched.setText("");
        AuthorsFetched.setText("");
        jTextArea1.setText("");
        KeywordsFetched.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleFetched = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AuthorsFetched = new javax.swing.JTextField();
        KeywordsFetched = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 194, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleFetched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleFetchedActionPerformed(evt);
            }
        });
        jPanel1.add(TitleFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, -1));

        jLabel1.setText("Titulo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Resumen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("Autores:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(AuthorsFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 300, -1));
        jPanel1.add(KeywordsFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 270, 20));

        jLabel4.setText("Palabras Claves:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, -1));

        AddButton.setBackground(new java.awt.Color(139, 171, 241));
        AddButton.setText("Agregar");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 140, 30));

        CloseButton.setBackground(new java.awt.Color(139, 171, 241));
        CloseButton.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 13)); // NOI18N
        CloseButton.setText("Cerrar");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 300, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddButtonActionPerformed
        if (validateFields()) {
            if (!getFormattedInformation()) {
            JOptionPane.showMessageDialog(this, "Ya existe una investigación con ese título.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_AddButtonActionPerformed

    private void TitleFetchedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TitleFetchedActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TitleFetchedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDirectAbstract(new App()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AuthorsFetched;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField KeywordsFetched;
    private javax.swing.JTextField TitleFetched;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
