/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metromendeleyloutphiruizzaheraldeen;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import datastructures.LinkedList;
import datastructures.LinkedListNode;
import datastructures.HashTable;
import datastructures.HashTableEntry;

/**
 *
 * @author ayahzaheraldeen
 */
public class AddDirectAbstract extends javax.swing.JFrame {

    private App app;

    /**
     * Creates new form AddDirectAbstract
     */
    public AddDirectAbstract(App app) {
        initComponents();
        this.app = app;
        this.setVisible(true);
        AddButton = new JButton("Agregar"); // Initialize Add button
        AddButton.addActionListener(e -> onAddButtonClicked()); // Add action listener
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1)); // Add button to
                                                                                                     // panel

    }

    private boolean validateFields() {
        if (TitleFetched.getText().isEmpty() ||
                TextFetched.getText().isEmpty() ||
                AuthorsFetched.getText().isEmpty() ||
                KeywordsFetched.getText().isEmpty()) {
            return false; // Return false if any field is empty
        }

        return true; // All fields are filled
    }

    private String getFormattedInformation() {
        String title = TitleFetched.getText().trim();
        String authors = AuthorsFetched.getText().trim();
        String text = TextFetched.getText().trim();
        String keywords = KeywordsFetched.getText().trim();

        // Split authors by comma or newline to handle multiple authors
        String[] authorsArray = authors.split("[,\n]");
        StringBuilder formattedInfo = new StringBuilder();

        // Title
        formattedInfo.append(title).append("\n\n");

        // Authors
        formattedInfo.append("Autores").append("\n");
        for (String author : authorsArray) {
            formattedInfo.append(author.trim()).append("\n");
        }

        // Abstract Text
        formattedInfo.append("Resumen ").append("\n").append(text).append("\n\n");

        // Keywords
        formattedInfo.append("Palabras Claves: ").append(keywords.replace(",", ", ")).append("\n");

        return formattedInfo.toString();
    }

    private void displayFormattedInfo(String formattedInfo) {
        // Example: Display formatted information in a message dialog
        JOptionPane.showMessageDialog(this, formattedInfo, "Formatted Information", JOptionPane.INFORMATION_MESSAGE);
        // You can also save this information to a file or database here
    }

    private void onAddButtonClicked() {
        if (validateFields()) {
            String formattedInfo = getFormattedInformation();
            displayFormattedInfo(formattedInfo); // Display or save formatted information
        } else {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        TitleFetched.setText("");
        AuthorsFetched.setText("");
        TextFetched.setText("");
        KeywordsFetched.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="GeneratedCode">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleFetched = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFetched = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AuthorsFetched = new javax.swing.JTextField();
        KeywordsFetched = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleFetched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleFetchedActionPerformed(evt);
            }
        });
        jPanel1.add(TitleFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        jLabel1.setText("Titulo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("Resumen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        TextFetched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFetchedActionPerformed(evt);
            }
        });
        jPanel1.add(TextFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 70));

        jLabel3.setText("Autores:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(AuthorsFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, -1));
        jPanel1.add(KeywordsFetched, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 100, 20));

        jLabel4.setText("Palabras Claves:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        AddButton.setText("Agregar");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddButtonActionPerformed
        String formattedInfo = getFormattedInformation();
        // Example: Show a message dialog with the formatted information
        JOptionPane.showMessageDialog(this, formattedInfo, "Formatted Information", JOptionPane.INFORMATION_MESSAGE);

        // Example: Save the formatted information to a file (adjust this as per your
        // needs)
        // saveFormattedInfoToFile(formattedInfo);

        // Optionally, clear the text fields after processing
        clearFields();
    }// GEN-LAST:event_AddButtonActionPerformed

    private void TitleFetchedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TitleFetchedActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TitleFetchedActionPerformed

    private void TextFetchedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextFetchedActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextFetchedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDirectAbstract.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDirectAbstract(new App()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AuthorsFetched;
    private javax.swing.JTextField KeywordsFetched;
    private javax.swing.JTextField TextFetched;
    private javax.swing.JTextField TitleFetched;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
